#!/usr/bin/env bash
#
# phase5_dedup_test.sh — verify alert deduplication (cooldown) behaviour.
#
# Blocker: AlertThreshold.Duration was declared and ignored, and there was no
# cooldown at all. A metric parked on the unhealthy side of its threshold fired
# one alert per scrape (~20 duplicates over 10 minutes).
#
# This script proves the fix two ways:
#   PHASE 1  deterministic  — injected clock, no wall time, exact fire counts
#   PHASE 2  live end-to-end — real SlackNotifier -> real HTTP receiver, real
#                              wall-clock cooldown, counts actual POSTs
#
# Usage:  bash /tmp/phase5_dedup_test.sh [repo-root]
# Exit:   0 = all assertions held, 1 = dedup regression

set -uo pipefail

REPO="${1:-/home/kntrnjb/Projects/prompts-mcp}"
PKG="$REPO/handlers"
LIVE_TEST="$PKG/zz_phase5_live_dedup_test.go"
RECEIVER_LOG="$(mktemp -t phase5-slack-XXXXXX.log)"
RECEIVER_PID=""

PASS=0
FAIL=0

green() { printf '\033[32m%s\033[0m\n' "$*"; }
red()   { printf '\033[31m%s\033[0m\n' "$*"; }
hdr()   { printf '\n\033[1m== %s ==\033[0m\n' "$*"; }

ok()   { green "  PASS  $*"; PASS=$((PASS+1)); }
bad()  { red   "  FAIL  $*"; FAIL=$((FAIL+1)); }

cleanup() {
  [[ -n "$RECEIVER_PID" ]] && kill "$RECEIVER_PID" 2>/dev/null
  rm -f "$LIVE_TEST" "$RECEIVER_LOG" "$RECEIVER_LOG.count"
}
trap cleanup EXIT

cd "$REPO" || { red "repo not found: $REPO"; exit 1; }

# ---------------------------------------------------------------------------
hdr "PHASE 1 — deterministic dedup (injected clock)"
# ---------------------------------------------------------------------------
# Covers: Duration pending window, cooldown suppression, recovery reset,
#         per-severity independence, and one-Slack-message-per-cooldown.

# NB: do NOT pipe `go test` into `grep -q` — with `pipefail` set, grep's early
# exit SIGPIPEs tee and the pipeline reports failure even when every test passed.
go test ./handlers/ -run 'TestDedup' -count=1 -v > /tmp/phase5_dedup_unit.log 2>&1
UNIT_RC=$?

while IFS= read -r line; do
  case "$line" in
    "--- PASS: "*) ok "${line#--- PASS: }" ;;
    "--- FAIL: "*) bad "${line#--- FAIL: }" ;;
  esac
done < /tmp/phase5_dedup_unit.log

if [[ $UNIT_RC -ne 0 ]]; then
  bad "deterministic dedup tests exited $UNIT_RC (see /tmp/phase5_dedup_unit.log)"
  sed -n '1,15p' /tmp/phase5_dedup_unit.log | sed 's/^/        /'
elif ! grep -q '^--- PASS' /tmp/phase5_dedup_unit.log; then
  bad "no dedup tests ran — check the -run filter"
fi

# ---------------------------------------------------------------------------
hdr "PHASE 2 — live end-to-end (real HTTP, real wall clock)"
# ---------------------------------------------------------------------------
# Scenario: metric held below threshold for 8 seconds, scraped every 200ms.
#   Duration = 1s, Cooldown = 3s
#   => 40 scrapes, fires at t~1s, t~4s, t~7s  = 3 alerts, 37 suppressed
# Pre-fix behaviour would be 40 alerts.

command -v python3 >/dev/null || { red "python3 required for the live receiver"; exit 1; }

PORT=$(python3 - <<'PY'
import socket
s = socket.socket(); s.bind(("127.0.0.1", 0)); print(s.getsockname()[1]); s.close()
PY
)

# Minimal Slack Incoming Webhook stand-in: 200 OK, one line per POST.
python3 - "$PORT" "$RECEIVER_LOG" <<'PY' &
import http.server, json, sys, threading
port, logpath = int(sys.argv[1]), sys.argv[2]
lock = threading.Lock()

class H(http.server.BaseHTTPRequestHandler):
    def do_POST(self):
        n = int(self.headers.get("Content-Length", 0))
        raw = self.rfile.read(n)
        try:
            text = json.loads(raw).get("text", "")
        except Exception:
            text = "<unparseable>"
        with lock, open(logpath, "a") as f:
            f.write(text.replace("\n", " ") + "\n")
        self.send_response(200); self.end_headers(); self.wfile.write(b"ok")
    def log_message(self, *a): pass

http.server.ThreadingHTTPServer(("127.0.0.1", port), H).serve_forever()
PY
RECEIVER_PID=$!
sleep 1

WEBHOOK="http://127.0.0.1:$PORT/services/TEST/PHASE5/DEDUP"

# Temporary in-package test that drives a real SlackNotifier on a real clock.
cat > "$LIVE_TEST" <<'GO'
package handlers

import (
	"os"
	"testing"
	"time"
)

// TestZZLivePhase5Dedup is generated by phase5_dedup_test.sh and removed after.
func TestZZLivePhase5Dedup(t *testing.T) {
	webhook := os.Getenv("PHASE5_WEBHOOK")
	if webhook == "" {
		t.Skip("PHASE5_WEBHOOK not set")
	}

	const metric = "prompts_all_avg_confidence" // must be an emitted metric
	saved := AlertMatrix
	defer func() { AlertMatrix = saved }()

	// Short-fuse threshold so the cooldown is observable in seconds.
	AlertMatrix = []AlertThreshold{{
		MetricName:  metric,
		Description: "live dedup harness",
		Threshold:   0.70,
		Severity:    SeverityError,
		Comparison:  ComparisonBelow,
		Duration:    1 * time.Second,
		Cooldown:    3 * time.Second,
		Action: AlertAction{
			Notification: "slack",
			Channel:      "#prompts-mcp-alerts",
			Message:      "confidence {{ .value }} below {{ .threshold }} on {{ .hostname }}",
			Runbook:      "/docs/runbooks/low-confidence-recovery.md",
			Dashboard:    "/d/prompts-registry-health/prompts-registry-health",
		},
	}}

	n := NewSlackNotifier(webhook)
	n.Sleep = func(time.Duration) {}
	ah := NewAlertHandlerWithNotifier(NewLogger(t.TempDir()), n)
	ah.SetFallbackPath(t.TempDir() + "/undelivered.jsonl")

	scrapes, fired := 0, 0
	deadline := time.Now().Add(8 * time.Second)
	for time.Now().Before(deadline) {
		scrapes++
		didFire, err := ah.CheckAndTrigger(metric, 0.40, SeverityError)
		if err != nil {
			t.Fatalf("delivery failed: %v", err)
		}
		if didFire {
			fired++
		}
		time.Sleep(200 * time.Millisecond)
	}

	t.Logf("PHASE5_RESULT scrapes=%d fired=%d", scrapes, fired)
	if scrapes < 30 {
		t.Fatalf("harness only managed %d scrapes; timing unreliable", scrapes)
	}
	if fired != 3 {
		t.Fatalf("expected 3 alerts (t~1s, ~4s, ~7s) from %d scrapes, got %d", scrapes, fired)
	}
}
GO

PHASE5_WEBHOOK="$WEBHOOK" go test ./handlers/ -run TestZZLivePhase5Dedup -count=1 -v -timeout 60s \
  > /tmp/phase5_dedup_live.log 2>&1
LIVE_RC=$?

SCRAPES=$(grep -o 'scrapes=[0-9]*' /tmp/phase5_dedup_live.log | head -1 | cut -d= -f2)
FIRED=$(grep -o 'fired=[0-9]*' /tmp/phase5_dedup_live.log | head -1 | cut -d= -f2)
DELIVERED=$(wc -l < "$RECEIVER_LOG" 2>/dev/null | tr -d ' ')
DELIVERED=${DELIVERED:-0}

echo "  scrapes above threshold : ${SCRAPES:-?}"
echo "  alerts fired            : ${FIRED:-?}"
echo "  Slack POSTs received    : $DELIVERED"
echo "  duplicates suppressed   : $(( ${SCRAPES:-0} - ${FIRED:-0} ))"

if [[ $LIVE_RC -eq 0 ]]; then
  ok "live cooldown held: ${SCRAPES} scrapes collapsed to ${FIRED} alerts"
else
  bad "live cooldown test failed (see /tmp/phase5_dedup_live.log)"
fi

if [[ "$DELIVERED" == "${FIRED:-x}" ]]; then
  ok "Slack receiver saw exactly $DELIVERED POST(s) — one per fired alert, no duplicates"
else
  bad "Slack receiver saw $DELIVERED POST(s) but $FIRED alert(s) fired"
fi

if [[ "$DELIVERED" -gt 0 ]] && grep -q "below" "$RECEIVER_LOG"; then
  ok "delivered message body is rendered (no unsubstituted template markers)"
else
  bad "delivered message body missing or unrendered"
fi

if grep -q '{{' "$RECEIVER_LOG" 2>/dev/null; then
  bad "unsubstituted template markers reached Slack"
else
  ok "no '{{' markers in any delivered message"
fi

# ---------------------------------------------------------------------------
hdr "SUMMARY"
# ---------------------------------------------------------------------------
echo "  passed: $PASS"
echo "  failed: $FAIL"
if [[ $FAIL -eq 0 ]]; then
  green "ALL DEDUP ASSERTIONS HELD"
  exit 0
fi
red "DEDUP REGRESSION DETECTED"
exit 1
